from __future__ import annotations

SUPPORTED_CONTENT_TYPES = {
    "application/pdf",
    "text/plain",
    "text/markdown",
    "text/csv",
    "application/json",
}

STRUCTURED_MODE_HEADING_DENSITY_MIN = 0.02
UNSTRUCTURED_MODE_HEADING_DENSITY_MAX = 0.005
SCANNED_MODE_AVG_LINE_LENGTH_MAX = 60

CHUNK_SIZE_TOKENS = 400
CHUNK_OVERLAP_TOKENS = 60

BM25_WEIGHT = 0.4
SEMANTIC_WEIGHT = 0.4
STRUCTURE_WEIGHT = 0.2

SUFFICIENCY_THRESHOLD = 0.65
MIN_EVIDENCE_CHARS = 100

CITATION_SNIPPET_LENGTH = 200
